### ISSUE TITLE
SyntaxError: Unexpected non-whitespace character after JSON at position 75 at JSON.parse (<anonymous>)

### ISSUE THREAD

**Issue by MichaelBlaettler** [pa-nic/homebridge-digitalSTROM#2]
Installed the AddOn on my Mac with OSX 14.3.1. Set-up worked as expected and connection with HomeKit worked well as well.

I can see and steer all supported devices, however, every time I trigger an action (e.g. switch on a light) I get the error message below and the plug-in reboots. 

Once rebooted, I can use it again until I trigger the next action.

[2/12/2024, 3:09:15 PM] [digitalSTROM] Esstisch -> On
[2/12/2024, 3:09:15 PM] SyntaxError: Unexpected non-whitespace character after JSON at position 75
    at JSON.parse (<anonymous>)
    at Object.callback (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/platform.ts:86:29)
    at /usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/webSocketClient.ts:110:51
    at Array.forEach (<anonymous>)
    at webSocketClient.handleMessage (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/webSocketClient.ts:110:20)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/webSocketClient.ts:64:14)
    at WebSocketConnection.emit (node:events:514:28)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-digitalstrom-plugin/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
[2/12/2024, 3:09:15 PM] Got SIGTERM, shutting down Homebridge...
[2/12/2024, 3:09:20 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/12/2024, 3:09:25 PM] [HB Supervisor] Restarting Homebridge...
[2/12/2024, 3:09:25 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[2/12/2024, 3:09:25 PM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 16948
[2/12/2024, 3:09:25 PM] Loaded config.json with 0 accessories and 2 platforms.
[2/12/2024, 3:09:25 PM] Loaded 29 cached accessories from cachedAccessories.
[2/12/2024, 3:09:26 PM] ---
[2/12/2024, 3:09:26 PM] Loaded plugin: homebridge-config-ui-x@4.55.1
[2/12/2024, 3:09:26 PM] Registering platform 'homebridge-config-ui-x.config'
[2/12/2024, 3:09:26 PM] ---
[2/12/2024, 3:09:26 PM] Loaded plugin: homebridge-digitalstrom-plugin@0.4.0
[2/12/2024, 3:09:26 PM] Registering platform 'homebridge-digitalstrom-plugin.DigitalStromPlugin'
[2/12/2024, 3:09:26 PM] ---
[2/12/2024, 3:09:26 PM] Loading 2 platforms...
[2/12/2024, 3:09:26 PM] [digitalSTROM] Initializing DigitalStromPlugin platform...

**Comment by pa-nic** [comment]
Can confirm this issue.
I'll commit an update with a quick fix. Thanks for reporting.
