### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by MichaelBlaettler** [pa-nic/homebridge-digitalSTROM#4]
Thanks for fixing the last bug. the Plugin runs rather stable now but I can see occasional errors in the Log which force a restart.
I cannot identify a clear root cause but can see in the log that it happens in irregular intervals (from 30min to couple of hours).

The homebridge Plugin runs on a Mac (M1) with MacOs 14.3.1.  

[2/19/2024, 4:09:35 PM] TypeError: Cannot read properties of undefined (reading '0')
    at Object.callback (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/platform.ts:87:40)
    at /usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/webSocketClient.ts:111:51
    at Array.forEach (<anonymous>)
    at webSocketClient.handleMessage (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/webSocketClient.ts:111:20)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/src/webSocketClient.ts:64:14)
    at WebSocketConnection.emit (node:events:514:28)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-digitalstrom-plugin/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-digitalstrom-plugin/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
[2/19/2024, 4:09:35 PM] Got SIGTERM, shutting down Homebridge...
[2/19/2024, 4:09:40 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by pa-nic** [comment]
It seems you're receiving websocket responses I don't get on my system and therefor cannot reproduce.

Nevertheless, I've added some sanity checks to the code, that should fix this.

**But before pushing the next update:**
Could you please do me a favor and post logs showing the error with homebridge running in debug mode.

Of interest would be the line "Received message" just before the error. i.e.
`Received message: {"command":"{\"type\":1,\"target\":\"event\",\"arguments\":[{\"type\":\"apartmentStatusChanged\"}]}"}`

**Comment by pa-nic** [comment]
I assume release v0.4.2 fixed this issue.

I'll keep this issue open for some time. But will close it soon because of inactivity...
